/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interprete;

import Abstracto.Instruccion;
import Analisis.parser;
import Analisis.scanner;
import Excepciones.Errores;
import Simbolo.Arbol;
import Simbolo.tablaSimbolos;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.LinkedList;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author crjav
 */
public class Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    private Arbol ultimoArbol;
    private tablaSimbolos ultimaTablaSimbolos;
    private File archivoActual; // Para guardar

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.ultimoArbol = null;
        this.ultimaTablaSimbolos = null;
        this.archivoActual = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemGuardarComo = new javax.swing.JMenuItem();
        jMenuEjecutar = new javax.swing.JMenu();
        jMenuItemEjecutar = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuItemReporteErrores = new javax.swing.JMenuItem();
        jMenuItemTablaSimbolos = new javax.swing.JMenuItem();
        jMenuItemAST = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaUSAC - Proyecto OLC1");
        setResizable(false);

        jMenuArchivo.setText("Archivo");
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(this::nuevoArchivo);
        jMenuArchivo.add(jMenuItemNuevo);
        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(this::abrirArchivo);
        jMenuArchivo.add(jMenuItemAbrir);
        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(this::guardarArchivo);
        jMenuArchivo.add(jMenuItemGuardar);
        jMenuItemGuardarComo.setText("Guardar Como");
        jMenuItemGuardarComo.addActionListener(this::guardarComoArchivo);
        jMenuArchivo.add(jMenuItemGuardarComo);
        jMenuBar1.add(jMenuArchivo);

        jMenuEjecutar.setText("Ejecutar");
        jMenuItemEjecutar.setText("Ejecutar");
        jMenuItemEjecutar.addActionListener(this::jButton1ActionPerformed);
        jMenuEjecutar.add(jMenuItemEjecutar);
        jMenuBar1.add(jMenuEjecutar);

        jMenuReportes.setText("Reportes");
        jMenuItemReporteErrores.setText("Reporte de Errores");
        jMenuItemReporteErrores.addActionListener(this::abrirReporteErrores);
        jMenuReportes.add(jMenuItemReporteErrores);
        jMenuItemTablaSimbolos.setText("Tabla de Simbolos");
        jMenuItemTablaSimbolos.addActionListener(this::abrirReporteSimbolos);
        jMenuReportes.add(jMenuItemTablaSimbolos);
        jMenuItemAST.setText("AST");
        jMenuItemAST.addActionListener(this::abrirAST);
        jMenuReportes.add(jMenuItemAST);
        jMenuBar1.add(jMenuReportes);

        setJMenuBar(jMenuBar1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Entrada");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 12));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Consola");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setFont(new java.awt.Font("Consolas", 0, 12));
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String texto = jTextArea1.getText();

            // VALIDAR QUE HAY TEXTO
            if (texto == null || texto.trim().isEmpty()) {
                jTextArea2.setText("ERROR: No hay texto para analizar");
                return;
            }

            //ejecutando el interprete
            scanner s = new scanner(new BufferedReader(new StringReader(texto)));
            parser p = new parser(s);
            var resultado = p.parse();

            // VALIDAR QUE EL PARSER RETORNÓ ALGO
            if (resultado == null || resultado.value == null) {
                jTextArea2.setText("ERROR: No se pudo parsear el código. Revisa la sintaxis.");
                return;
            }

            var ast = new Arbol((LinkedList<Instruccion>) resultado.value);
            var tabla = new tablaSimbolos();

            // Agregar errores léxicos del scanner al árbol
            for (var errorLexico : s.listaErrores) {
                ast.agregarError(errorLexico);
            }

            // Agregar errores sintácticos del parser al árbol
            for (var errorSintactico : p.listaErrores) {
                ast.agregarError(errorSintactico);
            }

            tabla.setNombre("GLOBAL");
            ast.setConsolas("");

            // Primera pasada: ejecutar todo excepto START, y almacenar START para ejecución posterior
            java.util.LinkedList<Abstracto.Instruccion> starts = new java.util.LinkedList<>();
            for (var a : ast.getInstrucciones()) {
                if (a == null) continue;
                if (a instanceof Instrucciones.Start) {
                    starts.add(a);
                    continue;
                }

                var resultadoInstruccion = a.interpretar(ast, tabla);
                if (resultadoInstruccion instanceof Errores) {
                    ast.agregarError((Errores) resultadoInstruccion);
                }
            }

            // Segunda pasada: ejecutar todos los START recogidos (ahora las funciones/métodos ya están registrados)
            for (var st : starts) {
                var resultadoStart = st.interpretar(ast, tabla);
                if (resultadoStart instanceof Errores) {
                    ast.agregarError((Errores) resultadoStart);
                }
            }

            // Mostrar PRIMERO todos los errores ordenados por línea, LUEGO las salidas
            String salidaFinal = "";
            if (!ast.getErrores().isEmpty()) {
                // Ordenar errores por línea
                ast.getErrores().sort((e1, e2) -> Integer.compare(e1.getLinea(), e2.getLinea()));

                for (var error : ast.getErrores()) {
                    salidaFinal += error.toString() + "\n";
                }
                salidaFinal += "\n"; // Línea en blanco
            }
            salidaFinal += ast.getConsolas();

            jTextArea2.setText(salidaFinal);

            // Guardar para los reportes
            this.ultimoArbol = ast;
            this.ultimaTablaSimbolos = tabla;

        } catch (Exception ex) {
            ex.printStackTrace();
            jTextArea2.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void abrirReporteErrores(java.awt.event.ActionEvent evt) {
        if (ultimoArbol != null && !ultimoArbol.getErrores().isEmpty()) {
            ReporteErrores ventana = new ReporteErrores(ultimoArbol.getErrores());
            ventana.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No hay errores para mostrar. Ejecuta un archivo primero.",
                    "Sin errores",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void abrirReporteSimbolos(java.awt.event.ActionEvent evt) {
        if (ultimaTablaSimbolos != null && ultimoArbol != null) {
            java.util.LinkedList<Simbolo.Simbolo> simbolos = new java.util.LinkedList<>(ultimoArbol.obtenerSimbolos(ultimaTablaSimbolos));

            // Incluir funciones y métodos en la tabla de símbolos
            var funciones = ultimoArbol.getFuncionesMetodos();
            for (var entry : funciones.entrySet()) {
                String id = entry.getKey();
                Abstracto.Instruccion instr = entry.getValue();
                Simbolo.Simbolo s;
                if (instr instanceof Instrucciones.DeclaracionFuncion) {
                    Instrucciones.DeclaracionFuncion df = (Instrucciones.DeclaracionFuncion) instr;
                    s = new Simbolo.Simbolo(df.tipo, id, "FUNCION", df.linea, df.columna, "GLOBAL");
                } else if (instr instanceof Instrucciones.DeclaracionMetodo) {
                    Instrucciones.DeclaracionMetodo dm = (Instrucciones.DeclaracionMetodo) instr;
                    s = new Simbolo.Simbolo(dm.tipo, id, "METODO", dm.linea, dm.columna, "GLOBAL");
                } else {
                    s = new Simbolo.Simbolo(new Simbolo.Tipo(Simbolo.tipoDato.VOID), id, "INSTRUCCION", 0, 0, "GLOBAL");
                }
                simbolos.add(s);
            }

            if (!simbolos.isEmpty()) {
                ReporteSimbolos ventana = new ReporteSimbolos(simbolos);
                ventana.setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No hay símbolos para mostrar. Ejecuta un archivo primero.",
                        "Sin símbolos",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No hay símbolos para mostrar. Ejecuta un archivo primero.",
                    "Sin símbolos",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void nuevoArchivo(java.awt.event.ActionEvent evt) {
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Deseas guardar los cambios antes de crear un nuevo archivo?",
                "Nuevo Archivo",
                javax.swing.JOptionPane.YES_NO_CANCEL_OPTION);

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            guardarArchivo(evt);
        } else if (opcion == javax.swing.JOptionPane.CANCEL_OPTION) {
            return;
        }

        jTextArea1.setText("");
        jTextArea2.setText("");
        archivoActual = null;
        ultimoArbol = null;
        ultimaTablaSimbolos = null;
        setTitle("JavaUSAC - Proyecto OLC1");
    }

    private void abrirArchivo(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos JavaUSAC (*.jc, *.ju)", "jc", "ju"));

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                jTextArea1.setText("");
                String linea;
                while ((linea = br.readLine()) != null) {
                    jTextArea1.append(linea + "\n");
                }
                archivoActual = archivo;
                setTitle("JavaUSAC - " + archivo.getName());
            } catch (IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al abrir el archivo: " + ex.getMessage(),
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void guardarArchivo(java.awt.event.ActionEvent evt) {
        if (archivoActual == null) {
            guardarComoArchivo(evt);
        } else {
            try (FileWriter fw = new FileWriter(archivoActual)) {
                fw.write(jTextArea1.getText());
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Archivo guardado correctamente",
                        "Guardar",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al guardar el archivo: " + ex.getMessage(),
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void guardarComoArchivo(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos JavaUSAC (*.jc)", "jc"));

        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            // Asegurar que tenga extensión .jc
            if (!archivo.getName().endsWith(".jc")) {
                archivo = new File(archivo.getAbsolutePath() + ".jc");
            }

            try (FileWriter fw = new FileWriter(archivo)) {
                fw.write(jTextArea1.getText());
                archivoActual = archivo;
                setTitle("JavaUSAC - " + archivo.getName());
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Archivo guardado correctamente",
                        "Guardar Como",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al guardar el archivo: " + ex.getMessage(),
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void abrirAST(java.awt.event.ActionEvent evt) {
        if (ultimoArbol == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No hay un árbol AST disponible. Ejecuta un archivo primero.",
                    "AST - Sin datos",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            String dot = ultimoArbol.generarDot();
            ASTViewer viewer = new ASTViewer(dot);
            viewer.setVisible(true);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al generar el AST: " + ex.getMessage(),
                    "AST - Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEjecutar;
    private javax.swing.JMenuItem jMenuItemAST;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemEjecutar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemGuardarComo;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemReporteErrores;
    private javax.swing.JMenuItem jMenuItemTablaSimbolos;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
