
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_TYPE = 42;
  public static final int PAR2 = 10;
  public static final int DOSPUNTOS = 13;
  public static final int PAR1 = 9;
  public static final int _new = 57;
  public static final int POT = 23;
  public static final int CHAR = 6;
  public static final int FIND = 63;
  public static final int LLAVE2 = 12;
  public static final int EQUALS = 26;
  public static final int LLAVE1 = 11;
  public static final int MENORQ = 28;
  public static final int ENTERO = 3;
  public static final int XOR = 34;
  public static final int DIFERENTE = 27;
  public static final int DOUBLE = 40;
  public static final int _do = 48;
  public static final int INT = 39;
  public static final int _switch = 51;
  public static final int NOT = 35;
  public static final int FINCADENA = 7;
  public static final int MENORIGUAL = 29;
  public static final int AND = 33;
  public static final int IGUAL = 25;
  public static final int CORCHETE2 = 15;
  public static final int OR = 32;
  public static final int _else = 45;
  public static final int BOOL = 41;
  public static final int CORCHETE1 = 14;
  public static final int DIV = 21;
  public static final int INCREMENTO = 54;
  public static final int _list = 56;
  public static final int UMENOS = 24;
  public static final int ID = 5;
  public static final int MAYORIGUAL = 31;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int RETURN = 64;
  public static final int TRUE = 36;
  public static final int DECREMENTO = 55;
  public static final int _break = 49;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int CADENA = 2;
  public static final int MENOS = 19;
  public static final int MOD = 22;
  public static final int START = 66;
  public static final int TOSTRING = 62;
  public static final int VOID = 65;
  public static final int _continue = 50;
  public static final int _if = 44;
  public static final int _default = 53;
  public static final int _while = 46;
  public static final int PUNTO = 17;
  public static final int MAYORQ = 30;
  public static final int _remove = 59;
  public static final int _for = 47;
  public static final int _case = 52;
  public static final int MULTI = 20;
  public static final int STRING = 43;
  public static final int FALSE = 37;
  public static final int VAR = 38;
  public static final int LENGTH = 61;
  public static final int ROUND = 60;
  public static final int _append = 58;
  public static final int PRINT = 8;
  public static final int MAS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CHAR",
  "FINCADENA",
  "PRINT",
  "PAR1",
  "PAR2",
  "LLAVE1",
  "LLAVE2",
  "DOSPUNTOS",
  "CORCHETE1",
  "CORCHETE2",
  "COMA",
  "PUNTO",
  "MAS",
  "MENOS",
  "MULTI",
  "DIV",
  "MOD",
  "POT",
  "UMENOS",
  "IGUAL",
  "EQUALS",
  "DIFERENTE",
  "MENORQ",
  "MENORIGUAL",
  "MAYORQ",
  "MAYORIGUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "TRUE",
  "FALSE",
  "VAR",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR_TYPE",
  "STRING",
  "_if",
  "_else",
  "_while",
  "_for",
  "_do",
  "_break",
  "_continue",
  "_switch",
  "_case",
  "_default",
  "INCREMENTO",
  "DECREMENTO",
  "_list",
  "_new",
  "_append",
  "_remove",
  "ROUND",
  "LENGTH",
  "TOSTRING",
  "FIND",
  "RETURN",
  "VOID",
  "START"
  };
}

